.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. nito_qt test_nito_qt
clean: FORCE
	$(MAKE) -C .. nito_qt_clean test_nito_qt_clean
check: FORCE
	$(MAKE) -C .. test_nito_qt_check
nito-qt nito-qt.exe: FORCE
	 $(MAKE) -C .. nito_qt
apk: FORCE
	$(MAKE) -C .. nito_qt_apk
