name: Build macOS
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
      - 'V*'
jobs:
  build-macos:
    runs-on: macos-15-large
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          brew install automake libtool pkg-config create-dmg
      - name: Build depends (without Qt)
        run: |
          cd depends
          make HOST=x86_64-apple-darwin NO_QT=1 -j$(sysctl -n hw.ncpu)
      - name: Build Nito
        run: |
          ./autogen.sh
          ./configure --prefix=$PWD/depends/x86_64-apple-darwin --disable-tests --disable-bench --without-gui
          make -j$(sysctl -n hw.ncpu)
      - name: Create tar.gz package
        run: |
          mkdir -p release/nito-3.0.0/bin
          cp src/nitod release/nito-3.0.0/bin/
          cp src/nito-cli release/nito-3.0.0/bin/
          cp src/nito-tx release/nito-3.0.0/bin/
          cp src/nito-wallet release/nito-3.0.0/bin/
          cp src/nito-util release/nito-3.0.0/bin/
          strip release/nito-3.0.0/bin/*
          cd release
          tar -czvf nito-3.0.0-x86_64-apple-darwin.tar.gz nito-3.0.0/
      - name: Upload tar.gz artifact
        uses: actions/upload-artifact@v4
        with:
          name: nito-3.0.0-x86_64-apple-darwin-tar
          path: release/nito-3.0.0-x86_64-apple-darwin.tar.gz
